/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getSearchAccess().getGroup(), "rule__Search__Group__0");
					put(grammarAccess.getRestaurantAccess().getGroup(), "rule__Restaurant__Group__0");
					put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
					put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
					put(grammarAccess.getSearchAccess().getSpecificationsAssignment_2(), "rule__Search__SpecificationsAssignment_2");
					put(grammarAccess.getRestaurantAccess().getArgumentsAssignment_2(), "rule__Restaurant__ArgumentsAssignment_2");
					put(grammarAccess.getAndAccess().getLeftSpecificationAssignment_1(), "rule__And__LeftSpecificationAssignment_1");
					put(grammarAccess.getAndAccess().getRightSpecificationAssignment_3(), "rule__And__RightSpecificationAssignment_3");
					put(grammarAccess.getOrAccess().getLeftSpecificationAssignment_1(), "rule__Or__LeftSpecificationAssignment_1");
					put(grammarAccess.getOrAccess().getRightSpecificationAssignment_3(), "rule__Or__RightSpecificationAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
